/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_faqrobot_map_echocancellation_Speex */

#ifndef _Included_org_faqrobot_map_echocancellation_Speex
#define _Included_org_faqrobot_map_echocancellation_Speex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_faqrobot_map_echocancellation_Speex
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_faqrobot_map_echocancellation_Speex_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_faqrobot_map_echocancellation_Speex
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_faqrobot_map_echocancellation_Speex_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     org_faqrobot_map_echocancellation_Speex
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_org_faqrobot_map_echocancellation_Speex_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

/*
 * Class:     org_faqrobot_map_echocancellation_Speex
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_faqrobot_map_echocancellation_Speex_encode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     org_faqrobot_map_echocancellation_Speex
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_faqrobot_map_echocancellation_Speex_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
